add data, querie and schema files
Ellyboi/vet-clinic-database pull request #1
Opened 2023-06-05 22:27 UTC by Ellyboi

2023-06-06 18:41 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Ellyboi 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ Queries are successful
✔️ Repo is generated using correct template
✔️ Sql commands are placed in the correct files

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-06 18:41 UTC, Ghiftee commented on README.md
- [ ] Your license is currently broken. Kindly fix it as it lets other developers know what they can and cannot do with your project. Also you can consider removing the part circled in the image below found underneath your license link. This would make your README more professional.

![Screenshot 2023-06-06 at 19 36 44 (2)](https://github.com/Ellyboi/vet-clinic-database/assets/64774936/80ff3947-3758-4b83-80b2-4cebf3d28a5e)

2023-06-06 18:41 UTC, Ghiftee commented on queries.sql
> +SELECT * FROM animals WHERE weight_kg BETWEEN 10.4 AND 17.3;
- [ ] Great job adding all the queries, however, you are missing these requirements. Kindly include them in your PR

![Screenshot 2023-06-06 at 19 34 55 (2)](https://github.com/Ellyboi/vet-clinic-database/assets/64774936/3f96f5f3-3068-4723-b407-7636fb159ace)

2023-06-07 20:13 UTC, VICTOR-CHUKWU approved these changes
Hi @Ellyboi , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 20:13 UTC, VICTOR-CHUKWU commented on README.md
> +- [Live Demo Link](<replace-with-your-deployment-URL>) -->
- [ ] [OPTIONAL AND IMPORTANT] as this project does not require deployment, kindly remove the live demo section

2023-06-07 20:25 UTC, merged